"""add is_active and updated_at to api_keys

Revision ID: 4850fdf01d7c
Revises: 99ba0801b0c2
Create Date: 2026-09-05 19:00:40.314389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4850fdf01d7c'
down_revision: Union[str, Sequence[str], None] = '99ba0801b0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('api_keys', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'updated_at')
    op.drop_column('api_keys', 'is_active')
    # ### end Alembic commands ###
