"""change token cost to numeric with 6 decimals

Revision ID: 99ba0801b0c2
Revises: cfc723854bea
Create Date: 2026-09-05 17:41:21.406084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ba0801b0c2'
down_revision: Union[str, Sequence[str], None] = 'cfc723854bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_provider_mappings', 'input_token_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=False)
    op.alter_column('model_provider_mappings', 'output_token_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=6, asdecimal=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_provider_mappings', 'output_token_cost',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('model_provider_mappings', 'input_token_cost',
               existing_type=sa.Numeric(precision=12, scale=6, asdecimal=False),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
