"""use uuid for primary and foreign keys

Revision ID: cfc723854bea
Revises: 0110689bf0c9
Create Date: 2026-09-05 15:30:20.947260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc723854bea'
down_revision: Union[str, Sequence[str], None] = '0110689bf0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_models_company_id_fkey', 'ai_models', type_='foreignkey')
    op.drop_constraint('api_keys_user_id_fkey', 'api_keys', type_='foreignkey')
    op.drop_constraint('user_credits_user_id_fkey', 'user_credits', type_='foreignkey')
    op.drop_constraint('model_provider_mappings_model_id_fkey', 'model_provider_mappings', type_='foreignkey')
    op.drop_constraint('model_provider_mappings_provider_id_fkey', 'model_provider_mappings', type_='foreignkey')
    op.alter_column('ai_companies', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               server_default=sa.text('gen_random_uuid()'),
               postgresql_using='id::uuid')
    op.alter_column('ai_models', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               server_default=sa.text('gen_random_uuid()'),
               postgresql_using='id::uuid')
    op.alter_column('ai_models', 'company_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='company_id::uuid')
    op.alter_column('ai_providers', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               server_default=sa.text('gen_random_uuid()'),
               postgresql_using='id::uuid')
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    op.alter_column('model_provider_mappings', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               server_default=sa.text('gen_random_uuid()'),
               postgresql_using='id::uuid')
    op.alter_column('model_provider_mappings', 'model_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='model_id::uuid')
    op.alter_column('model_provider_mappings', 'provider_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='provider_id::uuid')
    op.alter_column('user_credits', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               server_default=sa.text('gen_random_uuid()'),
               postgresql_using='id::uuid')
    op.alter_column('user_credits', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               server_default=sa.text('gen_random_uuid()'),
               postgresql_using='id::uuid')
    op.create_foreign_key('ai_models_company_id_fkey', 'ai_models', 'ai_companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('api_keys_user_id_fkey', 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_credits_user_id_fkey', 'user_credits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('model_provider_mappings_model_id_fkey', 'model_provider_mappings', 'ai_models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('model_provider_mappings_provider_id_fkey', 'model_provider_mappings', 'ai_providers', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_models_company_id_fkey', 'ai_models', type_='foreignkey')
    op.drop_constraint('api_keys_user_id_fkey', 'api_keys', type_='foreignkey')
    op.drop_constraint('user_credits_user_id_fkey', 'user_credits', type_='foreignkey')
    op.drop_constraint('model_provider_mappings_model_id_fkey', 'model_provider_mappings', type_='foreignkey')
    op.drop_constraint('model_provider_mappings_provider_id_fkey', 'model_provider_mappings', type_='foreignkey')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               server_default=None)
    op.alter_column('user_credits', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user_credits', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               server_default=None)
    op.alter_column('model_provider_mappings', 'provider_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('model_provider_mappings', 'model_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('model_provider_mappings', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               server_default=None)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('ai_providers', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               server_default=None)
    op.alter_column('ai_models', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('ai_models', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               server_default=None)
    op.alter_column('ai_companies', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               server_default=None)
    op.create_foreign_key('ai_models_company_id_fkey', 'ai_models', 'ai_companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('api_keys_user_id_fkey', 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_credits_user_id_fkey', 'user_credits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('model_provider_mappings_model_id_fkey', 'model_provider_mappings', 'ai_models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('model_provider_mappings_provider_id_fkey', 'model_provider_mappings', 'ai_providers', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###